### ISSUE TITLE
refactor

### ISSUE THREAD

**Issue by matin** [cuenca-mx/speid#61]
- [ ] using pytest-vcr #63 
- [ ] using pydantic for the form validation #64 
~- [ ] using pytest-flask-sqlalchemy to make sure all tests (pass or fail) are cleaned up at the end: https://pypi.org/project/pytest-flask-sqlalchemy/~
- [ ] using pytest-mock to mock the request / response to `cuenca` (to make it simpler to change vs having to use vcr with a staging or local server): https://pypi.org/project/pytest-mock/ #65 
- [ ] events should be committed at the same time as the associated event. Right now, we create the transaction, commit, create two events, and commit #66 
- [ ] move logic for events from the view to the model #67 
- [ ] remove any legacy code #68 
- [ ] make sure no network requests are being made during tests #69 
- [ ] swap postgres for mongo #70
